'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class P2014_BDTestFrancoisEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=P2014_BDTestFrancoisEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property tblCommande() As DbSet(Of tblCommande)
    Public Overridable Property tblFournisseur() As DbSet(Of tblFournisseur)
    Public Overridable Property tblFourniture() As DbSet(Of tblFourniture)
    Public Overridable Property tblFournitureCommande() As DbSet(Of tblFournitureCommande)
    Public Overridable Property tblFournitureFournisseur() As DbSet(Of tblFournitureFournisseur)
    Public Overridable Property tblFournitureHotel() As DbSet(Of tblFournitureHotel)
    Public Overridable Property tblChiffreHoraire() As DbSet(Of tblChiffreHoraire)
    Public Overridable Property tblEmploye() As DbSet(Of tblEmploye)
    Public Overridable Property tblEntretienFourniture() As DbSet(Of tblEntretienFourniture)
    Public Overridable Property tblHoraire() As DbSet(Of tblHoraire)
    Public Overridable Property tblChambre() As DbSet(Of tblChambre)
    Public Overridable Property tblClient() As DbSet(Of tblClient)
    Public Overridable Property tblEquipementGeneriqueChambre() As DbSet(Of tblEquipementGeneriqueChambre)
    Public Overridable Property tblEquipementRecreatif() As DbSet(Of tblEquipementRecreatif)
    Public Overridable Property tblEquipementRecreatifHotel() As DbSet(Of tblEquipementRecreatifHotel)
    Public Overridable Property tblFacture() As DbSet(Of tblFacture)
    Public Overridable Property tblForfait() As DbSet(Of tblForfait)
    Public Overridable Property tblHotel() As DbSet(Of tblHotel)
    Public Overridable Property tblPays() As DbSet(Of tblPays)
    Public Overridable Property tblProvince() As DbSet(Of tblProvince)
    Public Overridable Property tblReservationChambre() As DbSet(Of tblReservationChambre)
    Public Overridable Property tblReservationSalle() As DbSet(Of tblReservationSalle)
    Public Overridable Property tblSalle() As DbSet(Of tblSalle)
    Public Overridable Property tblTypeChambre() As DbSet(Of tblTypeChambre)
    Public Overridable Property tblVille() As DbSet(Of tblVille)

End Class
