'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblChiffreHoraire
    Public Property NoChiffreHoraire As Integer
    Public Property DateChiffre As Date
    Public Property HeureDebut As System.TimeSpan
    Public Property HeureFin As System.TimeSpan
    Public Property NoHoraire As Integer
    Public Property NoEmploye As Integer

    Public Overridable Property tblEmploye As tblEmploye
    Public Overridable Property tblHoraire As tblHoraire

End Class
