'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblEquipementRecreatifHotel
    Public Property CodeEquipementRecreatif As String
    Public Property CodeHotel As String
    Public Property QuantiteEquipement As Short

    Public Overridable Property tblEquipementRecreatif As tblEquipementRecreatif
    Public Overridable Property tblHotel As tblHotel

End Class
