'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblReservationChambre
    Public Property NoSeqReservChambre As Integer
    Public Property DateReservChambre As Date
    Public Property PrixReservChambre As Decimal
    Public Property ModePaiement As String
    Public Property StatutPaiement As String
    Public Property NbPersonne As Integer
    Public Property NoCarteCredit As String
    Public Property NomLocataire As String
    Public Property NoSeqChambre As Integer
    Public Property NoSeqClient As Integer

    Public Overridable Property tblChambre As tblChambre
    Public Overridable Property tblClient As tblClient
    Public Overridable Property tblFacture As ICollection(Of tblFacture) = New HashSet(Of tblFacture)

End Class
