'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCategorieFourniture
    Public Property CodeCategorie As String
    Public Property NomCategorie As String

    Public Overridable Property tblFourniture As ICollection(Of tblFourniture) = New HashSet(Of tblFourniture)

End Class
