'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblVille
    Public Property CodeVille As String
    Public Property NomVille As String
    Public Property CodeProvince As String

    Public Overridable Property tblClient As ICollection(Of tblClient) = New HashSet(Of tblClient)
    Public Overridable Property tblHotel As ICollection(Of tblHotel) = New HashSet(Of tblHotel)
    Public Overridable Property tblProvince As tblProvince

End Class
