'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblFournitureCommande
    Public Property NoCommande As Integer
    Public Property NoSeqFourniture As Integer
    Public Property QuantiteCommande As Integer

    Public Overridable Property tblCommande As tblCommande
    Public Overridable Property tblFourniture As tblFourniture

End Class
