'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblFournitureHotel
    Public Property CodeHotel As String
    Public Property CodeFourniture As String
    Public Property QuantiteMin As Short
    Public Property QuantiteMax As Integer
    Public Property QuantiteFournitureHotel As Nullable(Of Integer)

    Public Overridable Property tblFourniture As tblFourniture
    Public Overridable Property tblHotel As tblHotel

End Class
