'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblPrixTypeChambre
    Public Property NoSeqPrixTypeChambre As Integer
    Public Property DescPrixTypeChambre As String
    Public Property PrixTypeChambre As Decimal
    Public Property DateDebutPrix As Date
    Public Property DateFinPrix As Date
    Public Property CodeTypeChambre As String
    Public Property CodeHotel As String

    Public Overridable Property tblHotel As tblHotel
    Public Overridable Property tblTypeChambre As tblTypeChambre

End Class
