' ------------------------------------------------------------------------------------------- 
' Cr��e le : 10 novembre 2014
' Par : Fran�ois Morin
' Date de derni�re modification : 2014-12-15 08:33:05 
' -------------------------------------------------------------------------------------------

'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblClient
    Public Property NoSeqClient As Integer
    Public Property NomClient As String
    Public Property PrenomClient As String
    Public Property NoTelephone As String
    Public Property NoCellulaire As String
    Public Property AdresseClient As String
    Public Property AdresseSecondaireClient As String
    Public Property EmailClient As String
    Public Property MdpClient As String
    Public Property CodePostal As String
    Public Property NomEntreprise As String
    Public Property CodeVille As String

    Public Overridable Property tblReservationChambre As ICollection(Of tblReservationChambre) = New HashSet(Of tblReservationChambre)
    Public Overridable Property tblReservationSalle As ICollection(Of tblReservationSalle) = New HashSet(Of tblReservationSalle)
    Public Overridable Property tblVille As tblVille

End Class
