' ------------------------------------------------------------------------------------------- 
' Cr��e le : 10 novembre 2014
' Par : Fran�ois Morin
' Date de derni�re modification : 2014-12-15 08:33:05 
' -------------------------------------------------------------------------------------------

'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblChambreReservationChambre
    Public Property NoSeqChambre As Integer
    Public Property NoSeqReservChambre As Integer
    Public Property NbPersonne As Short
    Public Property NomLocataire As String
    Public Property PrenomLocataire As String
    Public Property DateDebutReservation As Date
    Public Property DateFinReservation As Date
    Public Property StatutChambreReservChambre As String

    Public Overridable Property tblChambre As tblChambre
    Public Overridable Property tblReservationChambre As tblReservationChambre
    Public Overridable Property tblForfait As ICollection(Of tblForfait) = New HashSet(Of tblForfait)

End Class
