' ------------------------------------------------------------------------------------------- 
' Cr��e le : 10 novembre 2014
' Par : Fran�ois Morin
' Date de derni�re modification : 2014-12-15 08:33:05 
' -------------------------------------------------------------------------------------------

'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblSalle
    Public Property CodeSalle As String
    Public Property NomSalle As String
    Public Property TypeSalle As String
    Public Property StatutSalle As String
    Public Property DetailSalle As String
    Public Property NbPlacesAssis As Short
    Public Property NbPlacesDebout As Short
    Public Property CodeHotel As String

    Public Overridable Property tblHotel As tblHotel
    Public Overridable Property tblReservationSalle As ICollection(Of tblReservationSalle) = New HashSet(Of tblReservationSalle)

End Class
