' ------------------------------------------------------------------------------------------- 
' Cr��e le : 10 novembre 2014
' Par : Fran�ois Morin
' Date de derni�re modification : 2014-12-15 08:33:05 
' -------------------------------------------------------------------------------------------

'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VueInventaire
    Public Property CodeHotel As String
    Public Property CodeFourniture As String
    Public Property DescFourniture As String
    Public Property CodeCategorie As String
    Public Property NomCategorie As String
    Public Property QuantiteFournitureHotel As Nullable(Of Integer)
    Public Property PrixFournitureFournisseur As Decimal
    Public Property QuantiteMin As Short
    Public Property QuantiteMax As Integer
    Public Property CodeFournisseur As String
    Public Property NomFournisseur As String

End Class
