'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblEquipementRecreatif
    Public Property CodeEquipementRecreatif As String
    Public Property NomEquipement As String
    Public Property StatutEquipement As String
    Public Property CategorieEquipement As String
    Public Property DateAquisition As Date
    Public Property DateFinGarantie As Date

    Public Overridable Property tblEquipementRecreatifHotel As ICollection(Of tblEquipementRecreatifHotel) = New HashSet(Of tblEquipementRecreatifHotel)
    Public Overridable Property tblForfait As ICollection(Of tblForfait) = New HashSet(Of tblForfait)

End Class
