'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblFournisseur
    Public Property CodeFournisseur As String
    Public Property NomFournisseur As String
    Public Property AdresseFournisseur As String
    Public Property NomRepresentant As String
    Public Property PrenomRepresentant As String

    Public Overridable Property tblCommande As ICollection(Of tblCommande) = New HashSet(Of tblCommande)
    Public Overridable Property tblFournitureFournisseur As ICollection(Of tblFournitureFournisseur) = New HashSet(Of tblFournitureFournisseur)

End Class
