'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblEmploye
    Public Property noEmploye As Integer
    Public Property nomEmploye As String
    Public Property prenomEmploye As String
    Public Property adresseEmploye As String
    Public Property noTelephoneEmploye As String
    Public Property motDePasseEmploye As String
    Public Property posteEmploye As String
    Public Property identifiantEmploye As String

End Class
