'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblFournitureReservationSalle
    Public Property NoSeqReservSalle As Integer
    Public Property CodeFourniture As String
    Public Property CodeSalle As String
    Public Property QuantiteFourniture As Short

    Public Overridable Property tblFourniture As tblFourniture
    Public Overridable Property tblEntretienFournitureSalle As ICollection(Of tblEntretienFournitureSalle) = New HashSet(Of tblEntretienFournitureSalle)
    Public Overridable Property tblReservationSalle As tblReservationSalle

End Class
