'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblForfait
    Public Property CodeForfait As String
    Public Property NomForfait As String
    Public Property PrixForfait As Decimal
    Public Property DescForfait As String
    Public Property NbNuit As Byte

    Public Overridable Property tblEquipementRecreatif As ICollection(Of tblEquipementRecreatif) = New HashSet(Of tblEquipementRecreatif)
    Public Overridable Property tblTypeChambre As ICollection(Of tblTypeChambre) = New HashSet(Of tblTypeChambre)

End Class
